<?php

namespace Database\Seeders;

use App\Enums\StatusEnums;
use App\Models\Settings\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_code_2' => 'AF', 'iso_code_3' => 'AFG', 'phone_code' => '93'],
            ['name' => 'Albania', 'iso_code_2' => 'AL', 'iso_code_3' => 'ALB', 'phone_code' => '355'],
            ['name' => 'Algeria', 'iso_code_2' => 'DZ', 'iso_code_3' => 'DZA', 'phone_code' => '213'],
            ['name' => 'Andorra', 'iso_code_2' => 'AD', 'iso_code_3' => 'AND', 'phone_code' => '376'],
            ['name' => 'Angola', 'iso_code_2' => 'AO', 'iso_code_3' => 'AGO', 'phone_code' => '244'],
            ['name' => 'Antigua and Barbuda', 'iso_code_2' => 'AG', 'iso_code_3' => 'ATG', 'phone_code' => '1-268'],
            ['name' => 'Argentina', 'iso_code_2' => 'AR', 'iso_code_3' => 'ARG', 'phone_code' => '54'],
            ['name' => 'Armenia', 'iso_code_2' => 'AM', 'iso_code_3' => 'ARM', 'phone_code' => '374'],
            ['name' => 'Australia', 'iso_code_2' => 'AU', 'iso_code_3' => 'AUS', 'phone_code' => '61'],
            ['name' => 'Austria', 'iso_code_2' => 'AT', 'iso_code_3' => 'AUT', 'phone_code' => '43'],
            ['name' => 'Azerbaijan', 'iso_code_2' => 'AZ', 'iso_code_3' => 'AZE', 'phone_code' => '994'],
            ['name' => 'Bahamas', 'iso_code_2' => 'BS', 'iso_code_3' => 'BHS', 'phone_code' => '1-242'],
            ['name' => 'Bahrain', 'iso_code_2' => 'BH', 'iso_code_3' => 'BHR', 'phone_code' => '973'],
            ['name' => 'Bangladesh', 'iso_code_2' => 'BD', 'iso_code_3' => 'BGD', 'phone_code' => '880'],
            ['name' => 'Barbados', 'iso_code_2' => 'BB', 'iso_code_3' => 'BRB', 'phone_code' => '1-246'],
            ['name' => 'Belarus', 'iso_code_2' => 'BY', 'iso_code_3' => 'BLR', 'phone_code' => '375'],
            ['name' => 'Belgium', 'iso_code_2' => 'BE', 'iso_code_3' => 'BEL', 'phone_code' => '32'],
            ['name' => 'Belize', 'iso_code_2' => 'BZ', 'iso_code_3' => 'BLZ', 'phone_code' => '501'],
            ['name' => 'Benin', 'iso_code_2' => 'BJ', 'iso_code_3' => 'BEN', 'phone_code' => '229'],
            ['name' => 'Bhutan', 'iso_code_2' => 'BT', 'iso_code_3' => 'BTN', 'phone_code' => '975'],
            ['name' => 'Bolivia', 'iso_code_2' => 'BO', 'iso_code_3' => 'BOL', 'phone_code' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code_2' => 'BA', 'iso_code_3' => 'BIH', 'phone_code' => '387'],
            ['name' => 'Botswana', 'iso_code_2' => 'BW', 'iso_code_3' => 'BWA', 'phone_code' => '267'],
            ['name' => 'Brazil', 'iso_code_2' => 'BR', 'iso_code_3' => 'BRA', 'phone_code' => '55'],
            ['name' => 'Brunei', 'iso_code_2' => 'BN', 'iso_code_3' => 'BRN', 'phone_code' => '673'],
            ['name' => 'Bulgaria', 'iso_code_2' => 'BG', 'iso_code_3' => 'BGR', 'phone_code' => '359'],
            ['name' => 'Burkina Faso', 'iso_code_2' => 'BF', 'iso_code_3' => 'BFA', 'phone_code' => '226'],
            ['name' => 'Burundi', 'iso_code_2' => 'BI', 'iso_code_3' => 'BDI', 'phone_code' => '257'],
            ['name' => 'Cabo Verde', 'iso_code_2' => 'CV', 'iso_code_3' => 'CPV', 'phone_code' => '238'],
            ['name' => 'Cambodia', 'iso_code_2' => 'KH', 'iso_code_3' => 'KHM', 'phone_code' => '855'],
            ['name' => 'Cameroon', 'iso_code_2' => 'CM', 'iso_code_3' => 'CMR', 'phone_code' => '237'],
            ['name' => 'Canada', 'iso_code_2' => 'CA', 'iso_code_3' => 'CAN', 'phone_code' => '1'],
            ['name' => 'Chad', 'iso_code_2' => 'TD', 'iso_code_3' => 'TCD', 'phone_code' => '235'],
            ['name' => 'Chile', 'iso_code_2' => 'CL', 'iso_code_3' => 'CHL', 'phone_code' => '56'],
            ['name' => 'China', 'iso_code_2' => 'CN', 'iso_code_3' => 'CHN', 'phone_code' => '86'],
            ['name' => 'Colombia', 'iso_code_2' => 'CO', 'iso_code_3' => 'COL', 'phone_code' => '57'],
            ['name' => 'Comoros', 'iso_code_2' => 'KM', 'iso_code_3' => 'COM', 'phone_code' => '269'],
            ['name' => 'Congo', 'iso_code_2' => 'CG', 'iso_code_3' => 'COG', 'phone_code' => '242'],
            ['name' => 'Costa Rica', 'iso_code_2' => 'CR', 'iso_code_3' => 'CRI', 'phone_code' => '506'],
            ['name' => 'Croatia', 'iso_code_2' => 'HR', 'iso_code_3' => 'HRV', 'phone_code' => '385'],
            ['name' => 'Cuba', 'iso_code_2' => 'CU', 'iso_code_3' => 'CUB', 'phone_code' => '53'],
            ['name' => 'Cyprus', 'iso_code_2' => 'CY', 'iso_code_3' => 'CYP', 'phone_code' => '357'],
            ['name' => 'Czechia', 'iso_code_2' => 'CZ', 'iso_code_3' => 'CZE', 'phone_code' => '420'],
            ['name' => 'Denmark', 'iso_code_2' => 'DK', 'iso_code_3' => 'DNK', 'phone_code' => '45'],
            ['name' => 'Djibouti', 'iso_code_2' => 'DJ', 'iso_code_3' => 'DJI', 'phone_code' => '253'],
            ['name' => 'Dominica', 'iso_code_2' => 'DM', 'iso_code_3' => 'DMA', 'phone_code' => '1-767'],
            ['name' => 'Dominican Republic', 'iso_code_2' => 'DO', 'iso_code_3' => 'DOM', 'phone_code' => '1-809'],
            ['name' => 'Ecuador', 'iso_code_2' => 'EC', 'iso_code_3' => 'ECU', 'phone_code' => '593'],
            ['name' => 'Egypt', 'iso_code_2' => 'EG', 'iso_code_3' => 'EGY', 'phone_code' => '20'],
            ['name' => 'El Salvador', 'iso_code_2' => 'SV', 'iso_code_3' => 'SLV', 'phone_code' => '503'],
            ['name' => 'Equatorial Guinea', 'iso_code_2' => 'GQ', 'iso_code_3' => 'GNQ', 'phone_code' => '240'],
            ['name' => 'Eritrea', 'iso_code_2' => 'ER', 'iso_code_3' => 'ERI', 'phone_code' => '291'],
            ['name' => 'Estonia', 'iso_code_2' => 'EE', 'iso_code_3' => 'EST', 'phone_code' => '372'],
            ['name' => 'Eswatini', 'iso_code_2' => 'SZ', 'iso_code_3' => 'SWZ', 'phone_code' => '268'],
            ['name' => 'Ethiopia', 'iso_code_2' => 'ET', 'iso_code_3' => 'ETH', 'phone_code' => '251'],
            ['name' => 'Fiji', 'iso_code_2' => 'FJ', 'iso_code_3' => 'FJI', 'phone_code' => '679'],
            ['name' => 'Finland', 'iso_code_2' => 'FI', 'iso_code_3' => 'FIN', 'phone_code' => '358'],
            ['name' => 'France', 'iso_code_2' => 'FR', 'iso_code_3' => 'FRA', 'phone_code' => '33'],
            ['name' => 'Gabon', 'iso_code_2' => 'GA', 'iso_code_3' => 'GAB', 'phone_code' => '241'],
            ['name' => 'Gambia', 'iso_code_2' => 'GM', 'iso_code_3' => 'GMB', 'phone_code' => '220'],
            ['name' => 'Georgia', 'iso_code_2' => 'GE', 'iso_code_3' => 'GEO', 'phone_code' => '995'],
            ['name' => 'Germany', 'iso_code_2' => 'DE', 'iso_code_3' => 'DEU', 'phone_code' => '49'],
            ['name' => 'Ghana', 'iso_code_2' => 'GH', 'iso_code_3' => 'GHA', 'phone_code' => '233'],
            ['name' => 'Greece', 'iso_code_2' => 'GR', 'iso_code_3' => 'GRC', 'phone_code' => '30'],
            ['name' => 'Grenada', 'iso_code_2' => 'GD', 'iso_code_3' => 'GRD', 'phone_code' => '1-473'],
            ['name' => 'Guatemala', 'iso_code_2' => 'GT', 'iso_code_3' => 'GTM', 'phone_code' => '502'],
            ['name' => 'Guinea', 'iso_code_2' => 'GN', 'iso_code_3' => 'GIN', 'phone_code' => '224'],
            ['name' => 'Guinea-Bissau', 'iso_code_2' => 'GW', 'iso_code_3' => 'GNB', 'phone_code' => '245'],
            ['name' => 'Guyana', 'iso_code_2' => 'GY', 'iso_code_3' => 'GUY', 'phone_code' => '592'],
            ['name' => 'Haiti', 'iso_code_2' => 'HT', 'iso_code_3' => 'HTI', 'phone_code' => '509'],
            ['name' => 'Honduras', 'iso_code_2' => 'HN', 'iso_code_3' => 'HND', 'phone_code' => '504'],
            ['name' => 'Hungary', 'iso_code_2' => 'HU', 'iso_code_3' => 'HUN', 'phone_code' => '36'],
            ['name' => 'Iceland', 'iso_code_2' => 'IS', 'iso_code_3' => 'ISL', 'phone_code' => '354'],
            ['name' => 'India', 'iso_code_2' => 'IN', 'iso_code_3' => 'IND', 'phone_code' => '91'],
            ['name' => 'Indonesia', 'iso_code_2' => 'ID', 'iso_code_3' => 'IDN', 'phone_code' => '62'],
            ['name' => 'Iran', 'iso_code_2' => 'IR', 'iso_code_3' => 'IRN', 'phone_code' => '98'],
            ['name' => 'Iraq', 'iso_code_2' => 'IQ', 'iso_code_3' => 'IRQ', 'phone_code' => '964'],
            ['name' => 'Ireland', 'iso_code_2' => 'IE', 'iso_code_3' => 'IRL', 'phone_code' => '353'],
            ['name' => 'Israel', 'iso_code_2' => 'IL', 'iso_code_3' => 'ISR', 'phone_code' => '972'],
            ['name' => 'Italy', 'iso_code_2' => 'IT', 'iso_code_3' => 'ITA', 'phone_code' => '39'],
            ['name' => 'Jamaica', 'iso_code_2' => 'JM', 'iso_code_3' => 'JAM', 'phone_code' => '1-876'],
            ['name' => 'Japan', 'iso_code_2' => 'JP', 'iso_code_3' => 'JPN', 'phone_code' => '81'],
            ['name' => 'Jordan', 'iso_code_2' => 'JO', 'iso_code_3' => 'JOR', 'phone_code' => '962'],
            ['name' => 'Kazakhstan', 'iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ', 'phone_code' => '7'],
            ['name' => 'Kenya', 'iso_code_2' => 'KE', 'iso_code_3' => 'KEN', 'phone_code' => '254'],
            ['name' => 'Kiribati', 'iso_code_2' => 'KI', 'iso_code_3' => 'KIR', 'phone_code' => '686'],
            ['name' => 'Korea (North)', 'iso_code_2' => 'KP', 'iso_code_3' => 'PRK', 'phone_code' => '850'],
            ['name' => 'Korea (South)', 'iso_code_2' => 'KR', 'iso_code_3' => 'KOR', 'phone_code' => '82'],
            ['name' => 'Kuwait', 'iso_code_2' => 'KW', 'iso_code_3' => 'KWT', 'phone_code' => '965'],
            ['name' => 'Kyrgyzstan', 'iso_code_2' => 'KG', 'iso_code_3' => 'KGZ', 'phone_code' => '996'],
            ['name' => 'Laos', 'iso_code_2' => 'LA', 'iso_code_3' => 'LAO', 'phone_code' => '856'],
            ['name' => 'Latvia', 'iso_code_2' => 'LV', 'iso_code_3' => 'LVA', 'phone_code' => '371'],
            ['name' => 'Lebanon', 'iso_code_2' => 'LB', 'iso_code_3' => 'LBN', 'phone_code' => '961'],
            ['name' => 'Lesotho', 'iso_code_2' => 'LS', 'iso_code_3' => 'LSO', 'phone_code' => '266'],
            ['name' => 'Liberia', 'iso_code_2' => 'LR', 'iso_code_3' => 'LBR', 'phone_code' => '231'],
            ['name' => 'Libya', 'iso_code_2' => 'LY', 'iso_code_3' => 'LBY', 'phone_code' => '218'],
            ['name' => 'Liechtenstein', 'iso_code_2' => 'LI', 'iso_code_3' => 'LIE', 'phone_code' => '423'],
            ['name' => 'Lithuania', 'iso_code_2' => 'LT', 'iso_code_3' => 'LTU', 'phone_code' => '370'],
            ['name' => 'Luxembourg', 'iso_code_2' => 'LU', 'iso_code_3' => 'LUX', 'phone_code' => '352'],
            ['name' => 'Madagascar', 'iso_code_2' => 'MG', 'iso_code_3' => 'MDG', 'phone_code' => '261'],
            ['name' => 'Malawi', 'iso_code_2' => 'MW', 'iso_code_3' => 'MWI', 'phone_code' => '265'],
            ['name' => 'Malaysia', 'iso_code_2' => 'MY', 'iso_code_3' => 'MYS', 'phone_code' => '60'],
            ['name' => 'Maldives', 'iso_code_2' => 'MV', 'iso_code_3' => 'MDV', 'phone_code' => '960'],
            ['name' => 'Mali', 'iso_code_2' => 'ML', 'iso_code_3' => 'MLI', 'phone_code' => '223'],
            ['name' => 'Malta', 'iso_code_2' => 'MT', 'iso_code_3' => 'MLT', 'phone_code' => '356'],
            ['name' => 'Marshall Islands', 'iso_code_2' => 'MH', 'iso_code_3' => 'MHL', 'phone_code' => '692'],
            ['name' => 'Mauritania', 'iso_code_2' => 'MR', 'iso_code_3' => 'MRT', 'phone_code' => '222'],
            ['name' => 'Mauritius', 'iso_code_2' => 'MU', 'iso_code_3' => 'MUS', 'phone_code' => '230'],
            ['name' => 'Mexico', 'iso_code_2' => 'MX', 'iso_code_3' => 'MEX', 'phone_code' => '52'],
            ['name' => 'Micronesia', 'iso_code_2' => 'FM', 'iso_code_3' => 'FSM', 'phone_code' => '691'],
            ['name' => 'Moldova', 'iso_code_2' => 'MD', 'iso_code_3' => 'MDA', 'phone_code' => '373'],
            ['name' => 'Monaco', 'iso_code_2' => 'MC', 'iso_code_3' => 'MCO', 'phone_code' => '377'],
            ['name' => 'Mongolia', 'iso_code_2' => 'MN', 'iso_code_3' => 'MNG', 'phone_code' => '976'],
            ['name' => 'Montenegro', 'iso_code_2' => 'ME', 'iso_code_3' => 'MNE', 'phone_code' => '382'],
            ['name' => 'Morocco', 'iso_code_2' => 'MA', 'iso_code_3' => 'MAR', 'phone_code' => '212'],
            ['name' => 'Mozambique', 'iso_code_2' => 'MZ', 'iso_code_3' => 'MOZ', 'phone_code' => '258'],
            ['name' => 'Myanmar', 'iso_code_2' => 'MM', 'iso_code_3' => 'MMR', 'phone_code' => '95'],
            ['name' => 'Namibia', 'iso_code_2' => 'NA', 'iso_code_3' => 'NAM', 'phone_code' => '264'],
            ['name' => 'Nauru', 'iso_code_2' => 'NR', 'iso_code_3' => 'NRU', 'phone_code' => '674'],
            ['name' => 'Nepal', 'iso_code_2' => 'NP', 'iso_code_3' => 'NPL', 'phone_code' => '977'],
            ['name' => 'Netherlands', 'iso_code_2' => 'NL', 'iso_code_3' => 'NLD', 'phone_code' => '31'],
            ['name' => 'New Zealand', 'iso_code_2' => 'NZ', 'iso_code_3' => 'NZL', 'phone_code' => '64'],
            ['name' => 'Nicaragua', 'iso_code_2' => 'NI', 'iso_code_3' => 'NIC', 'phone_code' => '505'],
            ['name' => 'Niger', 'iso_code_2' => 'NE', 'iso_code_3' => 'NER', 'phone_code' => '227'],
            ['name' => 'Nigeria', 'iso_code_2' => 'NG', 'iso_code_3' => 'NGA', 'phone_code' => '234'],
            ['name' => 'North Macedonia', 'iso_code_2' => 'MK', 'iso_code_3' => 'MKD', 'phone_code' => '389'],
            ['name' => 'Norway', 'iso_code_2' => 'NO', 'iso_code_3' => 'NOR', 'phone_code' => '47'],
            ['name' => 'Oman', 'iso_code_2' => 'OM', 'iso_code_3' => 'OMN', 'phone_code' => '968'],
            ['name' => 'Pakistan', 'iso_code_2' => 'PK', 'iso_code_3' => 'PAK', 'phone_code' => '92'],
            ['name' => 'Palau', 'iso_code_2' => 'PW', 'iso_code_3' => 'PLW', 'phone_code' => '680'],
            ['name' => 'Panama', 'iso_code_2' => 'PA', 'iso_code_3' => 'PAN', 'phone_code' => '507'],
            ['name' => 'Papua New Guinea', 'iso_code_2' => 'PG', 'iso_code_3' => 'PNG', 'phone_code' => '675'],
            ['name' => 'Paraguay', 'iso_code_2' => 'PY', 'iso_code_3' => 'PRY', 'phone_code' => '595'],
            ['name' => 'Peru', 'iso_code_2' => 'PE', 'iso_code_3' => 'PER', 'phone_code' => '51'],
            ['name' => 'Philippines', 'iso_code_2' => 'PH', 'iso_code_3' => 'PHL', 'phone_code' => '63'],
            ['name' => 'Poland', 'iso_code_2' => 'PL', 'iso_code_3' => 'POL', 'phone_code' => '48'],
            ['name' => 'Portugal', 'iso_code_2' => 'PT', 'iso_code_3' => 'PRT', 'phone_code' => '351'],
            ['name' => 'Qatar', 'iso_code_2' => 'QA', 'iso_code_3' => 'QAT', 'phone_code' => '974'],
            ['name' => 'Romania', 'iso_code_2' => 'RO', 'iso_code_3' => 'ROU', 'phone_code' => '40'],
            ['name' => 'Russia', 'iso_code_2' => 'RU', 'iso_code_3' => 'RUS', 'phone_code' => '7'],
            ['name' => 'Rwanda', 'iso_code_2' => 'RW', 'iso_code_3' => 'RWA', 'phone_code' => '250'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code_2' => 'KN', 'iso_code_3' => 'KNA', 'phone_code' => '1-869'],
            ['name' => 'Saint Lucia', 'iso_code_2' => 'LC', 'iso_code_3' => 'LCA', 'phone_code' => '1-758'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code_2' => 'VC', 'iso_code_3' => 'VCT', 'phone_code' => '1-784'],
            ['name' => 'Samoa', 'iso_code_2' => 'WS', 'iso_code_3' => 'WSM', 'phone_code' => '685'],
            ['name' => 'San Marino', 'iso_code_2' => 'SM', 'iso_code_3' => 'SMR', 'phone_code' => '378'],
            ['name' => 'Sao Tome and Principe', 'iso_code_2' => 'ST', 'iso_code_3' => 'STP', 'phone_code' => '239'],
            ['name' => 'Saudi Arabia', 'iso_code_2' => 'SA', 'iso_code_3' => 'SAU', 'phone_code' => '966'],
            ['name' => 'Senegal', 'iso_code_2' => 'SN', 'iso_code_3' => 'SEN', 'phone_code' => '221'],
            ['name' => 'Serbia', 'iso_code_2' => 'RS', 'iso_code_3' => 'SRB', 'phone_code' => '381'],
            ['name' => 'Seychelles', 'iso_code_2' => 'SC', 'iso_code_3' => 'SYC', 'phone_code' => '248'],
            ['name' => 'Sierra Leone', 'iso_code_2' => 'SL', 'iso_code_3' => 'SLE', 'phone_code' => '232'],
            ['name' => 'Singapore', 'iso_code_2' => 'SG', 'iso_code_3' => 'SGP', 'phone_code' => '65'],
            ['name' => 'Slovakia', 'iso_code_2' => 'SK', 'iso_code_3' => 'SVK', 'phone_code' => '421'],
            ['name' => 'Slovenia', 'iso_code_2' => 'SI', 'iso_code_3' => 'SVN', 'phone_code' => '386'],
            ['name' => 'Solomon Islands', 'iso_code_2' => 'SB', 'iso_code_3' => 'SLB', 'phone_code' => '677'],
            ['name' => 'Somalia', 'iso_code_2' => 'SO', 'iso_code_3' => 'SOM', 'phone_code' => '252'],
            ['name' => 'South Africa', 'iso_code_2' => 'ZA', 'iso_code_3' => 'ZAF', 'phone_code' => '27'],
            ['name' => 'South Korea', 'iso_code_2' => 'KR', 'iso_code_3' => 'KOR', 'phone_code' => '82'],
            ['name' => 'South Sudan', 'iso_code_2' => 'SS', 'iso_code_3' => 'SSD', 'phone_code' => '211'],
            ['name' => 'Spain', 'iso_code_2' => 'ES', 'iso_code_3' => 'ESP', 'phone_code' => '34'],
            ['name' => 'Sri Lanka', 'iso_code_2' => 'LK', 'iso_code_3' => 'LKA', 'phone_code' => '94'],
            ['name' => 'Sudan', 'iso_code_2' => 'SD', 'iso_code_3' => 'SDN', 'phone_code' => '249'],
            ['name' => 'Suriname', 'iso_code_2' => 'SR', 'iso_code_3' => 'SUR', 'phone_code' => '597'],
            ['name' => 'Sweden', 'iso_code_2' => 'SE', 'iso_code_3' => 'SWE', 'phone_code' => '46'],
            ['name' => 'Switzerland', 'iso_code_2' => 'CH', 'iso_code_3' => 'CHE', 'phone_code' => '41'],
            ['name' => 'Syria', 'iso_code_2' => 'SY', 'iso_code_3' => 'SYR', 'phone_code' => '963'],
            ['name' => 'Taiwan', 'iso_code_2' => 'TW', 'iso_code_3' => 'TWN', 'phone_code' => '886'],
            ['name' => 'Tajikistan', 'iso_code_2' => 'TJ', 'iso_code_3' => 'TJK', 'phone_code' => '992'],
            ['name' => 'Tanzania', 'iso_code_2' => 'TZ', 'iso_code_3' => 'TZA', 'phone_code' => '255'],
            ['name' => 'Thailand', 'iso_code_2' => 'TH', 'iso_code_3' => 'THA', 'phone_code' => '66'],
            ['name' => 'Timor-Leste', 'iso_code_2' => 'TL', 'iso_code_3' => 'TLS', 'phone_code' => '670'],
            ['name' => 'Togo', 'iso_code_2' => 'TG', 'iso_code_3' => 'TGO', 'phone_code' => '228'],
            ['name' => 'Tonga', 'iso_code_2' => 'TO', 'iso_code_3' => 'TON', 'phone_code' => '676'],
            ['name' => 'Trinidad and Tobago', 'iso_code_2' => 'TT', 'iso_code_3' => 'TTO', 'phone_code' => '1-868'],
            ['name' => 'Tunisia', 'iso_code_2' => 'TN', 'iso_code_3' => 'TUN', 'phone_code' => '216'],
            ['name' => 'Turkey', 'iso_code_2' => 'TR', 'iso_code_3' => 'TUR', 'phone_code' => '90'],
            ['name' => 'Turkmenistan', 'iso_code_2' => 'TM', 'iso_code_3' => 'TKM', 'phone_code' => '993'],
            ['name' => 'Tuvalu', 'iso_code_2' => 'TV', 'iso_code_3' => 'TUV', 'phone_code' => '688'],
            ['name' => 'Uganda', 'iso_code_2' => 'UG', 'iso_code_3' => 'UGA', 'phone_code' => '256'],
            ['name' => 'Ukraine', 'iso_code_2' => 'UA', 'iso_code_3' => 'UKR', 'phone_code' => '380'],
            ['name' => 'United Arab Emirates', 'iso_code_2' => 'AE', 'iso_code_3' => 'ARE', 'phone_code' => '971'],
            ['name' => 'United Kingdom', 'iso_code_2' => 'GB', 'iso_code_3' => 'GBR', 'phone_code' => '44'],
            ['name' => 'United States', 'iso_code_2' => 'US', 'iso_code_3' => 'USA', 'phone_code' => '1'],
            ['name' => 'Uruguay', 'iso_code_2' => 'UY', 'iso_code_3' => 'URY', 'phone_code' => '598'],
            ['name' => 'Uzbekistan', 'iso_code_2' => 'UZ', 'iso_code_3' => 'UZB', 'phone_code' => '998'],
            ['name' => 'Vanuatu', 'iso_code_2' => 'VU', 'iso_code_3' => 'VUT', 'phone_code' => '678'],
            ['name' => 'Vatican City', 'iso_code_2' => 'VA', 'iso_code_3' => 'VAT', 'phone_code' => '39'],
            ['name' => 'Venezuela', 'iso_code_2' => 'VE', 'iso_code_3' => 'VEN', 'phone_code' => '58'],
            ['name' => 'Vietnam', 'iso_code_2' => 'VN', 'iso_code_3' => 'VNM', 'phone_code' => '84'],
            ['name' => 'Yemen', 'iso_code_2' => 'YE', 'iso_code_3' => 'YEM', 'phone_code' => '967'],
            ['name' => 'Zambia', 'iso_code_2' => 'ZM', 'iso_code_3' => 'ZMB', 'phone_code' => '260'],
            ['name' => 'Zimbabwe', 'iso_code_2' => 'ZW', 'iso_code_3' => 'ZWE', 'phone_code' => '263']
        ];

        Country::insert($countries);
    }
}
